name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  phpstan:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: none

      - uses: actions/checkout@v4

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --error-format=github
